export const ADD_SOURCES = 'ADD_SOURCES';
export const ADD_NEXT_VIEW_PART_SOURCES = 'ADD_NEXT_VIEW_PART_SOURCES';
export const CLEAR_VIEW_SOURCES = 'CLEAR_VIEW_SOURCES';
export const ADD_FILTERED_NEWS = 'ADD_FILTERED_NEWS';
export const ADD_NEXT_VIEW_PART_NEWS = 'ADD_NEXT_VIEW_PART_NEWS';
export const CLEAR_VIEW_NEWS = 'CLEAR_VIEW_SOURCES';
export const ADD_SINGLE_NEWS = 'ADD_SINGLE_NEWS';